### ISSUE TITLE
Investigate updating the Net radiation calculation to a more standard process

### ISSUE THREAD

**Issue by qjhart** [CSTARS/spatial-cimis#36]
The current hourly net radiation calculations use a PERL script developed before grass had standard solar calculations.  There now exist standard grass packages for calculating solar radiation using the same theoretical background.  

However, it is not a drop in replacement for the current system.  We could investigate what the existing r.solar calculation to see if it can be modified to satisfy our needs, and contact the maintainers of that code to see if they would be willing to accept those changes.  This would have the benefit of moving the code to the standard grass package.

**Comment by rtrezza** [comment]
Quinn are you talking about r.sun described here ?
https://grass.osgeo.org/grass64/manuals/r.sun.html

**Comment by qjhart** [comment]
@rtrezza, yes. The problem with the r.sun calculations is that we have a methodology for selecting time intervals for our model.  r.sun doesn't do it that way, and instead they use multiple instantaneious versions. We'd have to get them to embrace an interval modifications.

**Comment by rtrezza** [comment]
We need to be careful if we want to use r.sun for our solar radiation calculations. No doubt we will have a more accurate Rs calculation taking into account the slope and aspect of the pixel. However, if we correct Rs for slope and aspect, then we would need also to correct Rnl (longwave radiation), which is a function of air temperature. So far air temperature is only corrected for elevation (lapse rate) so a north facing slope would have the same air temperature as a south facing slope if both are at the same elevation.  However, in reality, a south facing slope will receive more Rs (when corrected for slope/aspect) but will be hotter (more negative Rnl). My point is that we should not correct Rs without correcting Rnl at the same time; otherwise we will overestimate ETo on south facing slopes.

**Comment by qjhart** [comment]
@rtrezza, in reality, I believe that a CIMIS station is supposed to be on a flat surface, so we'd actually need to run one with and one without slope and aspect.  I think it's in the notes somewhere, that my suggestion for Rn for the ETo calculation would *not* take into account slope and aspect but *would* take into account any local horizon changes.  This would be represent a cimis station.

**Comment by rtrezza** [comment]
I agree with you Quinn; so for now let's forget about using r.sun and only take into account the horizon changes.  I need to do more research on the topic. Thanks
