### ISSUE TITLE
Investigate low radiation and K values for 7/22/2019

### ISSUE THREAD

**Issue by gjscheer-ucd** [CSTARS/spatial-cimis#81]
Radiation and K values are skewed much lower.  In the solar calculation log noticed this error which blew up the log:
```
sunrise:0500PST-B2 <- srter
day:0510PST-B2 <- 0500PST-B2
r.solpos year=2019 month=07 day=22 timezone=-8 sretr=sretr ssetr=ssetr ssha=ssha

r.heliosat -i year=2019 month=07 day=22 timezone=-8 hour=04 minute=60 elevin=Z@500m linkein=linkeT_0721@500m latitude=latitude@500m ssha=ssha;
WARNING: S_decode ==> Please fix the minute: 60
```

**Comment by qjhart** [comment]
We run the r.heliosat model at sunrise (sretr).  The time we use, is sunrise of the middle of the image.  Previously, I was rounding to the nearest minute.  That would mean that if sunrise occured in the last 30 seconds of the 59th minute, it would be rounded to 60.  That's what happened on 07/22.  I have fixed that (so that we take the floor of the minutes) [r.solpos](https://github.com/CSTARS/r.solpos/commit/0ef173c12ad2d4c823ccb9a3b82d6037ab7a4646)

And then reran 07/22 with 
``` bash
g.mapset location=solar mapset=20190722
# in solar/20190722
make --directory=~/spatial-cimis/g.cimis/etc/ -f solar.mk solar  | tee ~/20190722_solar.log
make --directory=~/spatial-cimis/g.cimis/etc/ -f solar.mk clean-tmp
# Then in cimis/20190722
g.mapset location=cimis mapset=20190722
rm /var/www/cimis/2019/07/22/*.png
make --directory=~/spatial-cimis/g.cimis/etc/ -f cimis.mk ETo html
